# Site settings
title: Josh Spicer
email: hello@joshspicer.com
description: The home of a Cambridge, MA based Software Engineer
baseurl: "" # the subpath of your site, e.g. /blog/
url: https://joshspicer.com # Site url. Place your path here, or leave blank to work local.
twitter_username: joshspicer_
github_username: joshspicer

site-links:
  - name: Home
    url: https://joshspicer.com
    icon: fas fa-home
    color: "#000"

social-links:
  - name: Instagram
    url: http://instagram.com/joshspicer_
    icon: fab fa-instagram
    color: "#F7C277"
    external: true
  - name: GitHub
    url: http://github.com/joshspicer
    icon: fab fa-github
    color: "#25292E"
    external: true
  - name: Linkedin
    url: http://linkedin.com/in/joshspicer
    icon: fab fa-linkedin
    color: "#6AABE9"
    external: true
  - name: Facebook
    url: https://facebook.com/spicer.josh
    icon: fab fa-facebook
    color: "#3B5998"
    external: true
  - name: Spotify
    url: https://open.spotify.com/user/joshspicer37
    icon: fab fa-spotify
    color: "#1db954"
    external: true

include: [".well-known"]

# Build settings
#markdown: redcarpet
highlighter: rouge
markdown_ext: markdown,mkdown,mkdn,mkd,md
#redcarpet:
#  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "fenced_code_blocks"]
permalink: pretty
plugins:
  - jekyll-redirect-from
